version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: ride-postgres
    environment:
      POSTGRES_USER: preeti
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ride_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: